server {
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    server_name jenkins.autotests.cloud www.jenkins.autotests.cloud;

    # ssl_certificate ...;
    # ssl_certificate_key ...;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/jenkins.access.log;
    error_log  /var/log/nginx/jenkins.error.log;

    location / {
        include /etc/nginx/proxy_params;
        proxy_pass          http://127.0.0.1:8082;
        proxy_read_timeout  90s;
        proxy_redirect      http://127.0.0.1:8082 https://jenkins.autotests.cloud;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name jenkins.autotests.cloud www.jenkins.autotests.cloud;
    return 301 https://$host$request_uri;
}
